### ISSUE TITLE
Link to Discord server and DaryNodes do not change color on hover + Contrast between hovered color in IP links

### ISSUE THREAD

**Issue by PjrCodes** [TrixNetwork/TrixNetwork.github.io#21]
Link to Discord server and DaryNodes do not change color on hovering. They remain a permanent light blue. 

Also, I believe the control in the hovered links is too much.

Hovered link color:
<img width="628" alt="Screen Shot 2022-04-20 at 15 05 53" src="https://user-images.githubusercontent.com/25995849/164198836-ca49457c-4428-44fa-963d-ec9fbb4e279c.png">

No change in the color of the actual href-links:
<img width="631" alt="Screen Shot 2022-04-20 at 15 06 44" src="https://user-images.githubusercontent.com/25995849/164199005-9da7e2a6-a177-473e-bc02-0a6553663676.png">

**Comment by nrbxyz** [comment]
fixed in #22 #23
